//Contact api Actions
export const contactApi = {
	CONTACT_INITIATED: 'CONTACT_INITIATED',
	CONTACT_SUCCESS: 'CONTACT_SUCCESS',
	CONTACT_FAILED: 'CONTACT_FAILED',
};

//Conversation related Actions
// (/conversations GET API)
export const conversationApi = {
	CONVERSATION_INITIATED: 'CONVERSATION_INITIATED',
	CONVERSATION_SUCCESS: 'CONVERSATION_SUCCESS',
	CONVERSATION_FAILED: 'CONVERSATION_FAILED',
};

// (/conversations POST API)
export const sendConversationApi = {
	SEND_CONVERSATION_INITIATED: 'SEND_CONVERSATION_INITIATED',
	SEND_CONVERSATION_SUCCESS: 'SEND_CONVERSATION_SUCCESS',
	SEND_CONVERSATION_FAILED: 'SEND_CONVERSATION_FAILED',
};

// (/conversations/:id GET API)
export const getConversationByIdApi = {
	GET_CONVERSATION_BYID_INITAITED: 'GET_CONVERSATION_BYID_INITAITED',
	GET_CONVERSATION_BYID_SUCCESS: 'GET_CONVERSATION_BYID_SUCCESS',
	GET_CONVERSATION_BYID_FAILED: 'GET_CONVERSATION_BYID_FAILED',
};


//Message related Actions
// (/conversations/:id GET API)
export const messageApi = {
	MESSAGE_INITIATED: 'MESSAGE_INITIATED',
	MESSAGE_SUCCESS: 'MESSAGE_SUCCESS',
	MESSAGE_FAILED: 'MESSAGE_FAILED',
};

// (/conversations/:id/messages POST API)
export const sendMessageApi = {
	SEND_MESSAGE_INITIATED: 'SEND_MESSAGE_INITIATED',
	SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
	SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',
};

// (/conversations/:id/messages/:messageId GET API)
export const getMessageByIdApi = {
	GET_MESSAGE_BYID_INITIATED: 'GET_MESSAGE_BYID_INITIATED',
	GET_MESSAGE_BYID_SUCCESS: 'GET_MESSAGE_BYID_SUCCESS',
	GET_MESSAGE_BYID_FAILED: 'GET_MESSAGE_BYID_FAILED',
};

// Socket Connection ActionTypes
export const connectSocket = {
	CONNECT_SOCKET_INITIATE: 'CONNECT_SOCKET_INITIATE',
	CONNECT_SOCKET_SUCCESS: 'CONNECT_SOCKET_SUCCESS',
	CONNECT_SOCKET_FAILED: 'CONNECT_SOCKET_FAILED',
};

// ActionTypes for Selected Data
export const addData = {
	ADD_DATA_INITIAED: 'ADD_DATA_INITIAED',
	ADD_DATA_SUCCESS: 'ADD_DATA_SUCCESS',
	ADD_DATA_FAILED: 'ADD_DATA_FAILED',
};
